### ISSUE TITLE
Problemas con Entidades Relaciones y Cardinalidades

### ISSUE THREAD

**Issue by Hantonson10** [Hantonson10/SpecialOlympics#3]
A ver chicos, Tenemos un problema con el E/R. Hoy lo subo para que le echéis un ojo pero mañana martes 1 de febrero tenemos que echarle un ojo urgentemente porque hay puntos que tenemos que tratar. Y si podemos agarrar a Diego y preguntarle todavía mejor

**Comment by MikeBarberan** [comment]
OK... supongo que se debe a lo ya comentado de las actividades y los eventos... Lo mejor es  coger a Diego por la solapa y que nos aclare el la cosa.

**Comment by MikeBarberan** [comment]
De acuerdo con los cambios en ALERGIA, DISCAPACIDAD... Como digo creo que sñolo faltarían las de las actividades y eventos y quizá los permisos, si es que los hay.

**Comment by SrCuesta** [comment]
En las relaciones N:M , ¿sería interesante pensar en el efecto niño coñón?.

**Comment by Hantonson10** [comment]
@SrCuesta  si las relaciones están bien hechas no habrá problema. La PK se compone de las FK y listo. El problema va a estar en controlar material que ya está entregado y esas cosas
