### ISSUE TITLE
Añadir scroll UNICO para navbar

### ISSUE THREAD

**Issue by iviDesatao** [Hantonson10/SpecialOlympics#5]
Si metes demasiados items en la navabar estos se stackean bien, pero al bajar para ver el resto hace scroll a toda la pagina. Hay que hacer que detecte en que posición está el mouse, si está encima de la navbar, hacer scroll ahi, si no, hacer scroll en el contenido.

**Comment by Hantonson10** [comment]
Creo que eso es con javascript. O bien en el navbar hacer un onscroll (no sé si existe) o bien hacer un document.onEvent / document.onScroll y gestionar el evento de scroll. 
Sé que se puede hacer esas cosas con la acción de copiar, que cuando haces un click dcho -> copiar se ejecuta una subrutina javascript. Esto será lo mismo pero con otro evento que disparará la rutina

**Comment by iviDesatao** [comment]
Tarea completada para la sidebar.
