### ISSUE TITLE
Falta resolver dudas

### ISSUE THREAD

**Issue by Hantonson10** [Hantonson10/SpecialOlympics#7]
El E/R está terminado pero faltan las dudas que vamos a preguntarle a David Berrueco. Mientras tanto, revisad el E/R y si creéis que está bien aprobadlo para mergearlo

**Comment by MikeBarberan** [comment]
Quizá así? Por mi parte nada que añadir

**Comment by Hantonson10** [comment]
Genial. Falta que reviséis el E/R
@MikeBarberan  Mañana te enseño cómo hacerlo
